# Generated by Django 3.2.7 on 2021-11-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basicchain1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('msghash', models.CharField(blank=True, max_length=80, null=True)),
                ('chainhash', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'basicchain_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Basicchain2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('msghash', models.CharField(blank=True, max_length=80, null=True)),
                ('chainhash', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'basicchain_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finalsig1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('msghash', models.CharField(blank=True, max_length=80, null=True)),
                ('chainhash', models.CharField(blank=True, max_length=80, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'finalsig_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finalsig2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('msghash', models.CharField(blank=True, max_length=80, null=True)),
                ('chainhash', models.CharField(blank=True, max_length=80, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'finalsig_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Firstsig1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('msghash', models.CharField(blank=True, max_length=80, null=True)),
                ('chainhash', models.CharField(blank=True, max_length=80, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'firstsig_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Firstsig2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('msghash', models.CharField(blank=True, max_length=80, null=True)),
                ('chainhash', models.CharField(blank=True, max_length=80, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'firstsig_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intervalsig1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('msghash', models.CharField(blank=True, max_length=80, null=True)),
                ('chainhash', models.CharField(blank=True, max_length=80, null=True)),
                ('action', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'intervalsig_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intervalsig2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('msghash', models.CharField(blank=True, max_length=80, null=True)),
                ('chainhash', models.CharField(blank=True, max_length=80, null=True)),
                ('action', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'intervalsig_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mutualchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('msghash', models.CharField(blank=True, max_length=80, null=True)),
                ('chainhash', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'mutualchain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhcBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipname', models.CharField(blank=True, max_length=50, null=True)),
                ('sip', models.CharField(max_length=15)),
                ('dipname', models.CharField(blank=True, max_length=50, null=True)),
                ('dip', models.CharField(blank=True, max_length=15, null=True)),
                ('sipsei', models.CharField(blank=True, max_length=50, null=True)),
                ('dipsei', models.CharField(blank=True, max_length=50, null=True)),
                ('sipsui', models.CharField(blank=True, max_length=50, null=True)),
                ('dipsui', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phc_basic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhcFinalsig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipname', models.CharField(blank=True, max_length=50, null=True)),
                ('sip', models.CharField(max_length=15)),
                ('dipname', models.CharField(blank=True, max_length=50, null=True)),
                ('dip', models.CharField(blank=True, max_length=15, null=True)),
                ('sipsei', models.CharField(blank=True, max_length=50, null=True)),
                ('dipsei', models.CharField(blank=True, max_length=50, null=True)),
                ('sipsui', models.CharField(blank=True, max_length=50, null=True)),
                ('dipsui', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('sign', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phc_finalsig',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhcFirstsig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipname', models.CharField(blank=True, max_length=50, null=True)),
                ('sip', models.CharField(max_length=15)),
                ('dipname', models.CharField(blank=True, max_length=50, null=True)),
                ('dip', models.CharField(blank=True, max_length=15, null=True)),
                ('sipsei', models.CharField(blank=True, max_length=50, null=True)),
                ('dipsei', models.CharField(blank=True, max_length=50, null=True)),
                ('sipsui', models.CharField(blank=True, max_length=50, null=True)),
                ('dipsui', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('sign', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phc_firstsig',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhcIntervalsig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipname', models.CharField(blank=True, max_length=50, null=True)),
                ('sip', models.CharField(max_length=15)),
                ('dipname', models.CharField(blank=True, max_length=50, null=True)),
                ('dip', models.CharField(blank=True, max_length=15, null=True)),
                ('sipsei', models.CharField(blank=True, max_length=50, null=True)),
                ('dipsei', models.CharField(blank=True, max_length=50, null=True)),
                ('sipsui', models.CharField(blank=True, max_length=50, null=True)),
                ('dipsui', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('interval', models.IntegerField(blank=True, null=True)),
                ('sign', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phc_intervalsig',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhcMutual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipname', models.CharField(blank=True, max_length=50, null=True)),
                ('sip', models.CharField(max_length=15)),
                ('dipname', models.CharField(blank=True, max_length=50, null=True)),
                ('dip', models.CharField(blank=True, max_length=15, null=True)),
                ('sipsei', models.CharField(blank=True, max_length=50, null=True)),
                ('dipsei', models.CharField(blank=True, max_length=50, null=True)),
                ('sipsui', models.CharField(blank=True, max_length=50, null=True)),
                ('dipsui', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phc_mutual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhcSalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipname', models.CharField(blank=True, max_length=50, null=True)),
                ('sip', models.CharField(max_length=15)),
                ('dipname', models.CharField(blank=True, max_length=50, null=True)),
                ('dip', models.CharField(blank=True, max_length=15, null=True)),
                ('sipsei', models.CharField(blank=True, max_length=50, null=True)),
                ('dipsei', models.CharField(blank=True, max_length=50, null=True)),
                ('sipsui', models.CharField(blank=True, max_length=50, null=True)),
                ('dipsui', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('salt', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'phc_salt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhcShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipname', models.CharField(blank=True, max_length=50, null=True)),
                ('sip', models.CharField(max_length=15)),
                ('dipname', models.CharField(blank=True, max_length=50, null=True)),
                ('dip', models.CharField(blank=True, max_length=15, null=True)),
                ('sipsei', models.CharField(blank=True, max_length=50, null=True)),
                ('dipsei', models.CharField(blank=True, max_length=50, null=True)),
                ('sipsui', models.CharField(blank=True, max_length=50, null=True)),
                ('dipsui', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('sharekey', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'phc_share',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saltchain1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('msghash', models.CharField(blank=True, max_length=80, null=True)),
                ('chainhash', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'saltchain_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saltchain2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('msghash', models.CharField(blank=True, max_length=80, null=True)),
                ('chainhash', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'saltchain_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sharechain1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('msghash', models.CharField(blank=True, max_length=80, null=True)),
                ('chainhash', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'sharechain_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sharechain2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('msghash', models.CharField(blank=True, max_length=80, null=True)),
                ('chainhash', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'sharechain_2',
                'managed': False,
            },
        ),
    ]
