# Generated by Django 3.2.7 on 2021-11-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhcUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('action', models.IntegerField()),
            ],
            options={
                'db_table': 'phc_user',
                'managed': False,
            },
        ),
    ]
